title: >
  Programming Language Foundations in Agda

description: >
  Programming Language Foundations in Agda

license: Creative Commons Attribution 4.0 International License
license-file: https://creativecommons.org/licenses/by/4.0/

# To include a new author, add them below in the order in which they are to be
# displayed in the author list. If they have made contributions as an author via
# GitHub, their username MUST be included in the list.
authors:
  - name: Philip Wadler
    email: wadler@inf.ed.ac.uk
    corresponding: true
    github_username: wadler
  - name: Wen Kokke
    email: wen.kokke@ed.ac.uk
    corresponding: true
    github_username: wenkokke
    twitter_username: wenkokke

google_analytics: "UA-125055580-1"

repository: plfa/plfa.github.io
branch: dev

baseurl: ""
url: "https://plfa.github.io"
markdown: kramdown
theme: minima
exclude:
  - "hs/"
  - "src/"
  - "extra/"
  - "vendor/"
  - "*.lagda"
  - "Gemfile"
  - "Gemfile.lock"
